### ISSUE TITLE
后台查询的菜单数据拼装成路由格式的数据

### ISSUE THREAD

**Issue by qiuqianquan** [guyan0319/go-admin#2]
你好，按照你的写法报如下错误：

Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
Occurred while linting C:\Code\vue-element-admin\src\store\modules\permission.js:27
    at SourceCode.getTokenBefore (C:\Code\vue-element-admin\node_modules\eslint\lib\token-store\index.js:303:18)
    at checkSpacingBefore (C:\Code\vue-element-admin\node_modules\eslint\lib\rules\template-curly-spacing.js:60:42)
    at TemplateElement (C:\Code\vue-element-admin\node_modules\eslint\lib\rules\template-curly-spacing.js:119:17)
    at C:\Code\vue-element-admin\node_modules\eslint\lib\util\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Code\vue-element-admin\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Code\vue-element-admin\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\Code\vue-element-admin\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (C:\Code\vue-element-admin\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (C:\Code\vue-element-admin\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
    at C:\Code\vue-element-admin\node_modules\eslint\lib\linter.js:752:32
    at Array.forEach (<anonymous>)
    at runRules (C:\Code\vue-element-admin\node_modules\eslint\lib\linter.js:747:15)
    at Linter._verifyWithoutProcessors (C:\Code\vue-element-admin\node_modules\eslint\lib\linter.js:899:31)
    at C:\Code\vue-element-admin\node_modules\eslint\lib\linter.js:955:35
    at Array.map (<anonymous>)

**Comment by guyan0319** [comment]
服务端返回的数据结果给我一下

**Comment by guyan0319** [comment]
是数据库是用的data目录下的sql文件吗？
正确的服务端返回数据结果是这样的
{
	"code": 20000,
	"data": [{
		"children": [{
			"children": [{
				"alwaysShow": true,
				"component": "/system/user/create/index",
				"hidden": false,
				"id": 27,
				"meta": {
					"icon": "#",
					"status": true,
					"title": "添加用户"
				},
				"name": "添加用户",
				"path": "/system/user/create",
				"pid": 2,
				"url": "/user/create"
			}, {
				"component": "/system/user/list/index",
				"hidden": false,
				"id": 28,
				"meta": {
					"icon": "#",
					"status": true,
					"title": "用户列表"
				},
				"name": "用户列表",
				"path": "/system/user/list",
				"pid": 2,
				"url": "/user/index"
			}, {
				"alwaysShow": true,
				"component": "/system/user/edit/index",
				"hidden": true,
				"id": 29,
				"meta": {
					"icon": "#",
					"status": true,
					"title": "用户编辑"
				},
				"name": "用户编辑",
				"path": "/system/user/edit/:id(\\d+)",
				"pid": 2,
				"url": "/user/edit"
			}],
			"component": "/system/user/index",
			"hidden": false,
			"id": 2,
			"meta": {
				"icon": "#",
				"status": true,
				"title": "用户管理"
			},
			"name": "用户管理",
			"path": "/system/user",
			"pid": 1,
			"url": "/user"
		}, {
			"component": "/system/menu/index",
			"hidden": false,
			"id": 3,
			"meta": {
				"icon": "#",
				"status": true,
				"title": "菜单管理"
			},
			"name": "菜单管理",
			"path": "/system/menu",
			"pid": 1,
			"url": "/menu"
		}, {
			"alwaysShow": true,
			"component": "/system/role/index",
			"hidden": false,
			"id": 26,
			"meta": {
				"icon": "#",
				"status": true,
				"title": "角色管理"
			},
			"name": "角色管理",
			"path": "/system/role",
			"pid": 1,
			"url": "/roles"
		}],
		"component": "#",
		"hidden": false,
		"id": 1,
		"meta": {
			"icon": "fafa-adjust",
			"status": true,
			"title": "系统管理"
		},
		"name": "系统管理",
		"path": "#",
		"pid": 0,
		"url": "#"
	}, {
		"alwaysShow": true,
		"children": [{
			"alwaysShow": true,
			"component": "/article/create/index",
			"hidden": false,
			"id": 31,
			"meta": {
				"icon": "#",
				"status": true,
				"title": "创建文章"
			},
			"name": "创建文章",
			"path": "/article/create",
			"pid": 30,
			"url": "/article/create"
		}, {
			"alwaysShow": true,
			"component": "/article/edit/index",
			"hidden": true,
			"id": 32,
			"meta": {
				"icon": "#",
				"status": true,
				"title": "文章编辑"
			},
			"name": "文章编辑",
			"path": "/article/edit/:id(\\d+)",
			"pid": 30,
			"url": "/article/edit"
		}, {
			"alwaysShow": true,
			"component": "/article/list/index",
			"hidden": false,
			"id": 33,
			"meta": {
				"icon": "#",
				"status": true,
				"title": "文章列表"
			},
			"name": "文章列表",
			"path": "/article/list",
			"pid": 30,
			"url": "/article/list"
		}],
		"component": "#",
		"hidden": false,
		"id": 30,
		"meta": {
			"icon": "#",
			"status": true,
			"title": "内容管理"
		},
		"name": "内容管理",
		"path": "#",
		"pid": 0,
		"url": "/article"
	}]
}

**Comment by shengbiaoguo** [comment]
> 你好，按照你的写法报如下错误：
> 
> Module build failed (from ./node_modules/eslint-loader/index.js): TypeError: Cannot read property 'range' of null Occurred while linting C:\Code\vue-element-admin\src\store\modules\permission.js:27 at SourceCode.getTokenBefore (C:\Code\vue-element-admin\node_modules\eslint\lib\token-store\index.js:303:18) at checkSpacingBefore (C:\Code\vue-element-admin\node_modules\eslint\lib\rules\template-curly-spacing.js:60:42) at TemplateElement (C:\Code\vue-element-admin\node_modules\eslint\lib\rules\template-curly-spacing.js:119:17) at C:\Code\vue-element-admin\node_modules\eslint\lib\util\safe-emitter.js:45:58 at Array.forEach () at Object.emit (C:\Code\vue-element-admin\node_modules\eslint\lib\util\safe-emitter.js:45:38) at NodeEventGenerator.applySelector (C:\Code\vue-element-admin\node_modules\eslint\lib\util\node-event-generator.js:251:26) at NodeEventGenerator.applySelectors (C:\Code\vue-element-admin\node_modules\eslint\lib\util\node-event-generator.js:280:22) at NodeEventGenerator.enterNode (C:\Code\vue-element-admin\node_modules\eslint\lib\util\node-event-generator.js:294:14) at CodePathAnalyzer.enterNode (C:\Code\vue-element-admin\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:632:23) at C:\Code\vue-element-admin\node_modules\eslint\lib\linter.js:752:32 at Array.forEach () at runRules (C:\Code\vue-element-admin\node_modules\eslint\lib\linter.js:747:15) at Linter._verifyWithoutProcessors (C:\Code\vue-element-admin\node_modules\eslint\lib\linter.js:899:31) at C:\Code\vue-element-admin\node_modules\eslint\lib\linter.js:955:35 at Array.map ()

替换 babel-eslint版本就行了 babel-eslint@8.0.2
