### ISSUE TITLE
前端页面无法正常打开

### ISSUE THREAD

**Issue by aclk** [guyan0319/go-admin#5]
环境：  MacBook Pro 2015
Node version: v10.16.3
```
xxxxxx $ npm run dev --fix

> vue-element-admin@4.2.1 dev /Users/arvin.he/work/github/go-admin/vue-element-admin
> vue-cli-service serve --open

 INFO  Starting development server...
 10% building 2/2 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:9527/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/arvin.he/work/github/go-admin/vue-element-admin/public
ℹ ｢wds｣: 404s will fallback to /index.html
 98% after emitting CopyPlugin

 WARNING  Compiled with 1 warnings                                                                                                                   12:12:58 AM

 warning  in ./src/store/modules/permission.js

Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
Occurred while linting /Users/arvin.he/work/github/go-admin/vue-element-admin/src/store/modules/permission.js:27
    at SourceCode.getTokenBefore (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/rules/template-curly-spacing.js:60:42)
    at TemplateElement (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/rules/template-curly-spacing.js:119:17)
    at listeners.(anonymous function).forEach.listener (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/linter.js:752:32)
    at Array.forEach (<anonymous>)
    at runRules (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/linter.js:747:15)
    at Linter._verifyWithoutProcessors (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/linter.js:899:31)
    at preprocess.map.textBlock (/Users/arvin.he/work/github/go-admin/vue-element-admin/node_modules/eslint/lib/linter.js:955:35)
    at Array.map (<anonymous>)

 @ ./src/store/modules sync \.js$
 @ ./src/store/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.1.1.245:9527/sockjs-node (webpack)/hot/dev-server.js ./src/main.js


  App running at:
  - Local:   http://localhost:9527/
  - Network: http://10.1.1.245:9527/

  Note that the development build is not optimized.
  To create a production build, run yarn build.
```

**Comment by guyan0319** [comment]
http://localhost:9527  访问这个不行吗？看你的输出的结果应该能打开的

**Comment by bbpLU** [comment]
遇到一模一样的问题，打开http://localhost:9527是空白

**Comment by iamk123** [comment]
![image](https://user-images.githubusercontent.com/45218419/126294391-c3dc9ca9-aad2-4e33-b42b-e70826a2755f.png)
ithubusercontent.com/45218419/126294391-c3dc9ca9-aad2-4e33-b42b-e70826a2755f.png)
啥问题

**Comment by iamk123** [comment]
我的解决办法：
还是前端node_modules的问题，得用作者提供的zip包，自己更新启动后虽然没报错，但是访问出来的就是空白页。
解压zip包后运行，再根据报错，自己添加提示缺少的依赖，我是tui-editor和node-sass两个方面的错误。
